### ISSUE TITLE
Ship our own credential helper on Linux

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/gitcreds#47]
Obviously, this is tricky for many reasons:
- should the credential helper call R? That is messy and not super reliable. Or should it be a standalone binary? That seems like a better option.
- how should be actually store credentials. We need to look at what gh does Linux. It apparently installs its own handler and stores credentials internally:
  ```
  root@99340efa4c28:~# cat .gitconfig
  [credential "https://github.com"]
	  helper =
	  helper = !/usr/bin/gh auth git-credential
  [credential "https://gist.github.com"]
	  helper =
	  helper = !/usr/bin/gh auth git-credential
  ```

**Comment by gaborcsardi** [comment]
Well, gh does implement a very simple credential helper that just stores the tokens in the gh config files, in plain text:
```
root@99340efa4c28:~# cat .config/gh/hosts.yml
github.com:
    oauth_token: <token>
    user: gaborcsardi
    git_protocol: https
```

So this is not any better than the built in "store" credential helper that stores the tokens in `~/.git-credentials`.

We could certainly have something like this in gitcreds, but it seems questionable to introduce yet another plain text file with credentials.... we could store it the same place as gh, though.
